### ISSUE TITLE
Compilation broken after https://github.com/xbmc/xbmc/pull/12675

### ISSUE THREAD

**Issue by asavah** [xbmc/peripheral.joystick#121]
After https://github.com/xbmc/xbmc/pull/12675 was merged it's no longer possible to build peripheral.joystick, 
gcc-7.2 output:
```
In file included from src/peripheral.joystick/src/addon.cpp:23:0:
src/peripheral.joystick/src/addon.h:29:7: warning: ‘CPeripheralJoystick’ declared with greater visibility than the type of its field ‘CPeripheralJoystick::<anonymous>’ [-Wattributes]
 class CPeripheralJoystick
       ^~~~~~~~~~~~~~~~~~~
src/peripheral.joystick/src/addon.h:29:7: warning: ‘CPeripheralJoystick’ declared with greater visibility than its base ‘kodi::addon::CAddonBase’ [-Wattributes]
src/peripheral.joystick/src/addon.cpp: In member function ‘virtual bool CPeripheralJoystick::SendEvent(const PERIPHERAL_EVENT*)’:
src/peripheral.joystick/src/addon.cpp:146:56: error: no matching function for call to ‘JOYSTICK::CJoystickManager::SendEvent(const PERIPHERAL_EVENT&)’
     bHandled = CJoystickManager::Get().SendEvent(*event);
                                                        ^
In file included from src/peripheral.joystick/src/addon.cpp:26:0:
src/peripheral.joystick/src/api/JoystickManager.h:132:10: note: candidate: bool JOYSTICK::CJoystickManager::SendEvent(const kodi::addon::PeripheralEvent&)
     bool SendEvent(const kodi::addon::PeripheralEvent& event);
          ^~~~~~~~~
src/peripheral.joystick/src/api/JoystickManager.h:132:10: note:   no known conversion for argument 1 from ‘const PERIPHERAL_EVENT’ to ‘const kodi::addon::PeripheralEvent&’
CMakeFiles/peripheral.joystick.dir/build.make:62: recipe for target 'CMakeFiles/peripheral.joystick.dir/src/addon.cpp.o' failed
make[3]: *** [CMakeFiles/peripheral.joystick.dir/src/addon.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from src/peripheral.joystick/src/storage/StorageManager.cpp:31:0:
src/peripheral.joystick/src/addon.h:29:7: warning: ‘CPeripheralJoystick’ declared with greater visibility than the type of its field ‘CPeripheralJoystick::<anonymous>’ [-Wattributes]
 class CPeripheralJoystick
       ^~~~~~~~~~~~~~~~~~~
src/peripheral.joystick/src/addon.h:29:7: warning: ‘CPeripheralJoystick’ declared with greater visibility than its base ‘kodi::addon::CAddonBase’ [-Wattributes]
```

**Comment by garbear** [comment]
https://github.com/xbmc/peripheral.joystick/pull/122
